import { Movie } from "../../model/movie";

export const placeholderMovies: Movie[] = [
    {
      id: 1,
      title: 'Interstellar',
      posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
      releaseDate: '2014-11-05',
      genreIds: [12, 18, 878],
      voteAverage: 8.3,
      voteCount: 23550,
      originalLanguage: 'en',
    },
    {
      id: 2,
      title: 'Inception',
      posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
      overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
      releaseDate: '2010-07-16',
      genreIds: [28, 878, 12],
      voteAverage: 8.3,
      voteCount: 30500,
      originalLanguage: 'en',
    },
    {
      id: 3,
      title: 'The Dark Knight',
      posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
      releaseDate: '2008-07-16',
      genreIds: [18, 28, 80],
      voteAverage: 8.4,
      voteCount: 24567,
      originalLanguage: 'en',
    },
    {
      id: 4,
      title: 'The Matrix',
      posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
      overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
      releaseDate: '1999-03-31',
      genreIds: [28, 878],
      voteAverage: 8.1,
      voteCount: 20245,
      originalLanguage: 'en',
    },
    {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
      {
        id: 1,
        title: 'Interstellar',
        posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        releaseDate: '2014-11-05',
        genreIds: [12, 18, 878],
        voteAverage: 8.3,
        voteCount: 23550,
        originalLanguage: 'en',
      },
      {
        id: 2,
        title: 'Inception',
        posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        releaseDate: '2010-07-16',
        genreIds: [28, 878, 12],
        voteAverage: 8.3,
        voteCount: 30500,
        originalLanguage: 'en',
      },
      {
        id: 3,
        title: 'The Dark Knight',
        posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        releaseDate: '2008-07-16',
        genreIds: [18, 28, 80],
        voteAverage: 8.4,
        voteCount: 24567,
        originalLanguage: 'en',
      },
      {
        id: 4,
        title: 'The Matrix',
        posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        releaseDate: '1999-03-31',
        genreIds: [28, 878],
        voteAverage: 8.1,
        voteCount: 20245,
        originalLanguage: 'en',
      },
    // ... add more movies as needed
  ];
  